### ISSUE TITLE
When multiple devices with the same serial number are present, you can only select the first

### ISSUE THREAD

**Issue by SophiaH67** [hyblocker/OpenVR-SpaceCalibrator#23]
![image](https://github.com/user-attachments/assets/62b3ba7f-183d-41b8-b8a6-ae8b47c6c6fd)

I got in this scenario by messing around with steamvr drivers, so it's not urgent.

When multiple devices exist with the same serial number, only the first one is selectable in the UI.

When I select a different device, and click the 2nd device with the same id, it does nothing (not even select the first one).

The first device in the list still is selectable.

**Comment by hyblocker** [comment]
Fixed in an upcoming version.
